### ISSUE TITLE
Unable to build on latest rust nightly

### ISSUE THREAD

**Issue by DCRichards** [LedgerHQ/ledger-nanos-sdk#11]
Unable to build on latest Rust nightly with latest version. Rust compiler is suggesting to add `#![feature(const_fn_trait_bound)]`.

## Versions
* rustc 1.54.0-nightly (4de757209 2021-05-01)
* cargo 1.53.0-nightly (f3e13226d 2021-04-30)

## Stack

```shell
rust_1      | error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
rust_1      |    --> /usr/local/cargo/git/checkouts/ledger-nanos-sdk-f77eb1a6021b7ee5/56c5859/src/nvm.rs:181:6
rust_1      |     |
rust_1      | 181 | impl<T> AtomicStorage<T> where T: Copy {
rust_1      |     |      ^
rust_1      |     |
rust_1      |     = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
rust_1      |     = help: add `#![feature(const_fn_trait_bound)]` to the crate attributes to enable
rust_1      |
rust_1      | error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
rust_1      |    --> /usr/local/cargo/git/checkouts/ledger-nanos-sdk-f77eb1a6021b7ee5/56c5859/src/nvm.rs:237:6
rust_1      |     |
rust_1      | 237 | impl<T, const N: usize> Collection<T, N> where T: Copy {
rust_1      |     |      ^
rust_1      |     |
rust_1      |     = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
rust_1      |     = help: add `#![feature(const_fn_trait_bound)]` to the crate attributes to enable
```

**Comment by kingofpayne** [comment]
I can reproduce the issue. It was working with `rustc 1.53.0-nightly` and is broken with `rustc 1.54.0-nightly`.

**Comment by yhql** [comment]
Thanks for reporting this ! Would https://github.com/LedgerHQ/ledger-nanos-sdk/pull/13 be an acceptable solution ?

**Comment by DCRichards** [comment]
Thanks @yhql, looks good to me, I'm still learning so it was useful to see how you resolved it. Also great to see Rust in action at Ledger.
